stages:
  - build
  - deploy

.base:
  image: docker
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  only:
    - dev
    - master

build:
  extends: .base
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker build --build-arg MODE="production" --compress -t "${CI_REGISTRY_IMAGE}:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID" .
    - docker push "${CI_REGISTRY_IMAGE}:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID"


deploy_production:
  extends: .base
  stage: deploy
  tags:
    - proconsult-runner
  script:
    - docker rm -f front
    - docker run --restart=always -p 80:80 -d --name front "${CI_REGISTRY_IMAGE}:$CI_BUILD_REF_NAME-$CI_PIPELINE_ID"
    - docker logout "${CI_REGISTRY}"

